channels:
  - alvaro_sofar
  - conda-forge
  - defaults
dependencies:
  - arm-none-eabi-gcc=9_2020_q2_update
  - openocd-xpack=0.10.0_15
  - cmake-xpack=3.18.3_1
  - make=4.2.1
  - ninja=1.10.1
  - python=3.8.6
  - pyserial==3.5
  - pip
  - pip:
      - memfault-cli==0.2.0
      - python-dotenv==0.15.0
      - gitpython==3.1.12
      - pyyaml==5.4.1
  - lcov=1.15
  - clang-tools=11.0.0
  - cppcheck=2.1
  - gcovr
