version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            conda create -n xMoonJelly_fw

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build


          
