version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            conda env create -n xMoonJelly_fw --file environment.yml
      - run: 
          name: set up environment
          command: |
            conda init zsh
            conda activate xMoonJelly_fw
            source ~/.zshrc
      - run: 
          name: python test
          command: python conda_python_test.py      

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build


          
