version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            conda env create -f environment.yml
            source activate xMoonJelly_fw
      - run: python conda_python_test.py      

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build


          
