version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            conda create -n xMoonJelly_fw
            conda init zsh
            conda activate xMoonJelly_fw
            conda env -f update environment.yml
            conda list

      - run: python conda_python_test.py      

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build


          
