version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            conda env create -f environment.yml
      - run: 
          name: Run Tests
          command: |
            source activate xMoonJelly_fw

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build


          
