version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      
    steps:
      - checkout
      - run:
          name: create environment
          command: |
            conda env create -n xMoonJelly_fw --file environment.yml
      - run:
          name: set up conda in new shell and make build
          command: |
            conda init zsh
            source ~/.zshrc
            conda activate xMoonJelly_fw
            conda list
            python conda_python_test.py
            pwd
            ls
            cd demos/STM32/RT-STM32F103-STM3210E_EVAL-FATFS-USB
            make -j

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build


          
