version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
      
    steps:
      - checkout
      - run:
          name: Install dependencies, set up environment, and run test
          command: |
            conda env create -n xMoonJelly_fw --file environment.yml
            conda init zsh
            source ~/.zshrc
            conda activate xMoonJelly_fw
            conda list
            python conda_python_test.py
            pwd
            ls

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build


          
